# Generated by Django 4.1.7 on 2023-03-19 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sits', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(0, '16:00'), (1, '16:30'), (2, '17:00'), (3, '17:30'), (4, '18:00'), (5, '18:30'), (6, '19:00'), (7, '19:30'), (8, '20:00'), (9, '20:30'), (10, '21:00'), (11, '21:30'), (12, '22:00'), (13, '22:30'), (14, '23:00')], default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_customer', to=settings.AUTH_USER_MODEL)),
                ('tables', models.ManyToManyField(related_name='booked_tables', to='bookings.table')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
