# Generated by Django 4.1.7 on 2023-03-28 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='One', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='One', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tables',
            field=models.ManyToManyField(blank=True, to='bookings.table'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='sits',
            field=models.IntegerField(default=4),
        ),
    ]
